language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_VERSION=3.4.* COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.3
          env: SYMFONY_VERSION=4.4.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.4snapshot
          env: SYMFONY_VERSION=5.0.*
    allow_failures:
        - php: nightly

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - COMPOSER_FLAGS="--prefer-dist"

before_install:
    - composer self-update
    - |
      if [ "$SYMFONY_VERSION" != "" ]; then
           sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
      fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install: composer update $COMPOSER_FLAGS --no-interaction
